<a href="https://colab.research.google.com/github/Idan-Alter/OU-22961-Deep-Learning/blob/main/22961_1_6_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.tensor(2., requires_grad=True)
y = x**2
z = y+x
z.backward()
print(x.grad)

tensor(5.)


In [ ]:
x = torch.tensor([2., 3.], requires_grad=True)
y = x[0]*x[1]
y.backward()
print(x.grad)

tensor([3., 2.])


In [ ]:
x = torch.tensor([2., 3.], requires_grad=True)
y = torch.tensor([4., 5.], requires_grad=True)
w = x.sum()**2
z = w + y.sum()**3 + x[0] + y[1]
z.backward()
print(x.grad, y.grad, sep='\n')

tensor([11., 10.])
tensor([243., 244.])


In [ ]:
x = torch.tensor([2., 3.], requires_grad=True)
y = torch.tensor([4., 5.], requires_grad=True)
w = x.sum()**2
s = w.detach()
z = s + y.sum()**3 + x[0] + y[1]
z.backward()
print(x.grad, y.grad, sep='\n')

tensor([1., 0.])
tensor([243., 244.])


In [ ]:
y = torch.zeros(10, dtype=int)
x = torch.tensor(2., requires_grad=True)
for i in range(10):
  z = 2*x
  while torch.rand(1)<0.7:
    z = 2*z
  z.backward()
  y[i]   = x.grad
  x.grad = None
print(y)

tensor([   2,   64,    2,    4,    8, 4096,   32,   64,    4,    4])


In [ ]:
y = torch.zeros(10, dtype=int)
x = torch.tensor(2., requires_grad=True)
for i in range(10):
  z = 2*x
  while torch.rand(1)<0.7:
    z = 2*z
  z.backward()
  y[i] = x.grad
print(y)

tensor([ 4,  6,  8, 24, 26, 34, 50, 52, 56, 64])


In [ ]:
y = torch.zeros(5)
for i in range(5):
  x = torch.randn(1, requires_grad=True)
  if x>0:
     z = torch.exp(x)
  else:
      z = -x
  z.backward()
  y[i] = x.grad
print(y)

tensor([ 3.0476,  2.8047, -1.0000,  2.0189,  1.3605])
