<a href="https://colab.research.google.com/github/Idan-Alter/OU-22961-Deep-Learning/blob/main/22961_1_5_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.tensor([1, 2, 3, 4])
print(x==1)

tensor([ True, False, False, False])


In [ ]:
y = torch.tensor([1]*x.numel())
print(x, y, x==y, sep='\n')

tensor([1, 2, 3, 4])
tensor([1, 1, 1, 1])
tensor([ True, False, False, False])


In [ ]:
A = torch.arange(9).reshape(3,3)
B = torch.arange(3)
print(A, B, A+B, sep='\n')

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 1, 2])
tensor([[ 0,  2,  4],
        [ 3,  5,  7],
        [ 6,  8, 10]])


In [ ]:
B.expand_as(A)

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

In [ ]:
B.storage()

 0
 1
 2
[torch.LongStorage of size 3]

In [ ]:
C = B.expand_as(A).clone()

In [ ]:
B.reshape(3,1).expand_as(A)

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])

In [ ]:
B.reshape(1,3).expand_as(A)

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

In [ ]:
A = torch.arange(3).reshape(3,1)
B = torch.arange(4).reshape(1,4)
print(A, B, A+B, sep='\n')

tensor([[0],
        [1],
        [2]])
tensor([[0, 1, 2, 3]])
tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])


In [ ]:
A = torch.arange(6).reshape(3,2)
B = torch.arange(5).reshape(1,5)
print(A, B, sep='\n')
A+B

tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[0, 1, 2, 3, 4]])


RuntimeError: ignored

In [ ]:
A = torch.arange(24).reshape(2,3,4)
B = torch.tensor([0,1,2,3])
C = B.expand_as(A)
D = A+B
print(A.size(), B.size(), C, D, sep='\n')


torch.Size([2, 3, 4])
torch.Size([4])
tensor([[[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]],

        [[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]]])
tensor([[[ 0,  2,  4,  6],
         [ 4,  6,  8, 10],
         [ 8, 10, 12, 14]],

        [[12, 14, 16, 18],
         [16, 18, 20, 22],
         [20, 22, 24, 26]]])


In [ ]:
for i in range(C.size()[0]):
  for j in range(C.size()[1]):
    for k in range(C.size()[2]):
        assert(C[i,j,k]==B[k])