<a href="https://colab.research.google.com/github/Idan-Alter/OU-22961-Deep-Learning/blob/main/22961_1_2_tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([5, 6, 7, 8])
print(x + y)

tensor([ 6,  8, 10, 12])


In [ ]:
print(x - y, x * y, x / y, x ** y, sep='\n')

tensor([-4, -4, -4, -4])
tensor([ 5, 12, 21, 32])
tensor([0.2000, 0.3333, 0.4286, 0.5000])
tensor([    1,    64,  2187, 65536])


In [ ]:
x = torch.ones(size=(10**5,))
y = torch.randint(low=0, high=10, size=(10**5,))

In [ ]:
x.numel()

<function Tensor.numel>

In [ ]:
%%timeit
x*y

The slowest run took 19.69 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 196 µs per loop


In [ ]:
%%timeit
for i in range(x.numel()):
  x[i]*y[i]

1 loop, best of 5: 652 ms per loop


In [ ]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([5, 6, 7, 8])
print(x@y,x==1,sep='\n')

tensor(70)
tensor([ True, False, False, False])


In [ ]:
x=x.reshape(1,4)
y=y.reshape(4,1)
print(x,y,x@y,y@x,sep='\n')

tensor([[1, 2, 3, 4]])
tensor([[5],
        [6],
        [7],
        [8]])
tensor([[70]])
tensor([[ 5, 10, 15, 20],
        [ 6, 12, 18, 24],
        [ 7, 14, 21, 28],
        [ 8, 16, 24, 32]])


# Reductions

In [ ]:
x =  torch.ones(size=(3,))
y =  torch.ones(size=(3,3))
z =  torch.ones(size=(3,3,3))

print(x.norm(),y.min(),z.sum(),sep='\n')

tensor(1.7321)
tensor(1.)
tensor(27.)


In [ ]:
x =  torch.arange(24).reshape(2,3,4)
print(x, x.size())

y = x.sum()
print(y, y.size())

z = x.sum(axis=0)
print(z, z.size())

w = x.sum(axis=1)
print(w, w.size())

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) torch.Size([2, 3, 4])
tensor(276) torch.Size([])
tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]) torch.Size([3, 4])
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]]) torch.Size([2, 4])
