<a href="https://colab.research.google.com/github/Idan-Alter/OU-22961-Deep-Learning/blob/main/22961_1_1_tensor_initialization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.tensor([[1,2], [3,4]])
print(x,
      x.shape,
      x.dtype,
      sep='\n')

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64


In [ ]:
x = torch.tensor([1.0, 2, 3, 4])
print(x,
      x.shape,
      x.dtype,
      sep='\n')

tensor([1., 2., 3., 4.])
torch.Size([4])
torch.float32


In [ ]:
x = torch.arange(9)
print(x,
      x.shape,
      x.dtype,
      sep='\n')

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([9])
torch.int64


In [ ]:
y = torch.eye(3,dtype=torch.bool)
print(y,
      y.shape,
      y.dtype,
      sep='\n')

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])
torch.Size([3, 3])
torch.bool


In [ ]:
z = torch.randn(size=[2, 3, 3])

In [ ]:
print(x,y,z,sep='\n')

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])
tensor([[[-0.3805,  0.2403,  0.3717],
         [ 0.5420,  1.2810, -0.5281],
         [ 1.8960, -1.1024, -0.1697]],

        [[ 2.4900, -1.9578, -1.2096],
         [ 0.7143,  0.3503,  0.5913],
         [ 0.8357, -0.6526, -0.2560]]])
