<a href="https://colab.research.google.com/github/Idan-Alter/OU-22961-Deep-Learning/blob/main/22961_1_3_indexing_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
x = torch.arange(10).reshape(2,5)
print(x)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [ ]:
print(x[1,2], x[0,-1], sep='\n')

tensor(7)
tensor(4)


In [ ]:
y = torch.zeros(size=(2,3,4))
y[1,0,0] = -2
y[-1,-1,-1] =  1 
print(y)

tensor([[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[-2.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  1.]]])


In [ ]:
y[1, 1:2, 0:4:2]=100 
print(y)

tensor([[[  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.]],

        [[ -2.,   0.,   0.,   0.],
         [100.,   0., 100.,   0.],
         [  0.,   0.,   0.,   1.]]])


In [ ]:
print(y[y>0])

tensor([100., 100.,   1.])


In [ ]:
z = y>0
print(z, y[z], sep='\n')

tensor([[[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]],

        [[False, False, False, False],
         [ True, False,  True, False],
         [False, False, False,  True]]])
tensor([100., 100.,   1.])


In [ ]:
print(y[[False,True]])

tensor([[[ -2.,   0.,   0.,   0.],
         [100.,   0., 100.,   0.],
         [  0.,   0.,   0.,   1.]]])


In [ ]:
y[1,:,:]

tensor([[ -2.,   0.,   0.,   0.],
        [100.,   0., 100.,   0.],
        [  0.,   0.,   0.,   1.]])