<a href="https://colab.research.google.com/github/Idan-Alter/OU-22961-Deep-Learning/blob/main/22961_1_4_economizing_memory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

# View or Copy

In [ ]:
x = torch.arange(2*4*5).reshape(shape=(2,4,5))
y = x[:, 0::2, 2:5]
print(x, y, sep='\n')

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]])
tensor([[[ 2,  3,  4],
         [12, 13, 14]],

        [[22, 23, 24],
         [32, 33, 34]]])


In [ ]:
y[-1] = 100
print(y, x, sep='\n')

tensor([[[  2,   3,   4],
         [ 12,  13,  14]],

        [[100, 100, 100],
         [100, 100, 100]]])
tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21, 100, 100, 100],
         [ 25,  26,  27,  28,  29],
         [ 30,  31, 100, 100, 100],
         [ 35,  36,  37,  38,  39]]])


In [ ]:
z    = x[:,0::2,2:5].clone()
z[0] = 100
print(z, x, sep='\n')

tensor([[[100, 100, 100],
         [100, 100, 100]],

        [[100, 100, 100],
         [100, 100, 100]]])
tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21, 100, 100, 100],
         [ 25,  26,  27,  28,  29],
         [ 30,  31, 100, 100, 100],
         [ 35,  36,  37,  38,  39]]])


In [ ]:
x     = torch.arange(5)
index = (x>=2) & (x<4)
y     = x[index]
y[-1] = 0
print(x, index, y, sep='\n')

tensor([0, 1, 2, 3, 4])
tensor([False, False,  True,  True, False])
tensor([2, 0])


# In Place Ops

In [ ]:
x = torch.ones(5)
address = id(x)
x = torch.exp(x)
print(address == id(x))

False


In [ ]:
address = id(x)
x[:]    = torch.exp(x)
print(address == id(x))

True


In [ ]:
x = torch.ones(5)
print(x)
torch.exp_(x)
print(x)

tensor([1., 1., 1., 1., 1.])
tensor([2.7183, 2.7183, 2.7183, 2.7183, 2.7183])
